### PR TITLE
fix duplicated test-execution, show test results in the console

### PR DESCRIPTION
**Pull request by alwanof**

### CODE REVIEW

**Comment by Vooha-QualiTlabs** [comment]
@alwanof thank you for creating a pr, could you share the video/image reference for the issue of duplicated test execution?

**Comment by alwanof** [comment]
> @alwanof thank you for creating a pr, could you share the video/image reference for the issue of duplicated test execution?

I sent you a screen recording

**Comment by alwanof** [comment]
could you check the following plz:
https://youtu.be/yev5IsVrr1E

**Comment by Vooha-QualiTlabs** [comment]
okay, thank you @alwanof .
Yes, we have this duplication issue when the scripts/builds run in parallel, to avoid that we have put a time gap between the start of two parallel builds. It is nice to see that you updated the same.

**Review by Vooha-QualiTlabs — APPROVED** [review]

**Comment by Vooha-QualiTlabs** [comment]
@alwanof  pushed and published - https://www.npmjs.com/package/testcafe-reporter-xray-jira/v/1.1.0

**Comment by Vooha-QualiTlabs** [comment]
@alwanof I tried running the tests with the latest version, I am not getting the results in the console

**Comment by alwanof** [comment]
I still see old code stuff, did you run: gulp build?

**Comment by Vooha-QualiTlabs** [comment]
Hi @alwanof, yes, sorry. it is there now with v 1.1.1. I just checked, it is working fine. Thank you for contribution to this.

**Pull request merged**
